### ISSUE TITLE
Better error handling and error messaging

### ISSUE THREAD

**Issue by binarypatrick** [binarypatrick/Prune#7]
**Describe the bug**
Unhandled error when folder is write only

**To Reproduce**
Create a directory and make write only, then try to prune

**Expected behavior**
Better error handling and error messaging

**Screenshots**
Unhandled exception. System.UnauthorizedAccessException: Access to the path '<filepath>' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at BinaryPatrick.Prune.Services.DirectoryService.DeleteFiles(IEnumerable`1 files)
   at BinaryPatrick.Prune.Services.PruneService.PruneFiles()
   at BinaryPatrick.Prune.Program.<>c.<Main>b__0_0(PruneOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at BinaryPatrick.Prune.Program.Main(String[] args)
./backup.sh: line 39: 13384 Aborted                 prune --path $DIRECTORY --keep-hourly 24 --keep-daily 3 --keep-weekly 6 --keep-monthly 18

**Runtime (please complete the following information):**
 - OS: Raspbian

**Comment by binarypatrick** [comment]
Resolved with release v1.0.2
